modLoader = "javafml"
loaderVersion = "[51,)"
displayURL = "${modUrl}"
logoFile = "logo.png"
authors = "${modAuthor}"
license = "MIT"

[[mods]]
modId = "${modId}"
displayName = "${modName}"
version = "${minecraftVersion}-${modVersion}"
description = "${modDescription}"

[modproperties.${modId}]
incompatibleMods = ["betterthirdperson", "customcameraview", "nimble", "valkyrienskies"]

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"
