[versions]
minecraft = "1.21.1"
forge = "1.21.1-52.0.23"
neoforge = "21.1.60"
fabric-loader = "0.16.0"
fabric-api = "0.102.0+1.21.1"
mixin = "0.8.5"
forgeconfigapiport = "21.1.0"
wthit-common = "mojmap-12.2.2"
wthit-forge = "forge-12.2.2"
wthit-neoforge = "neo-12.2.2"
wthit-fabric = "fabric-12.2.2"
jade-common = "5427896" # 1.21-15.0.4-fabric-api
jade-forge = "5427896" # temporarily use common artifact for compilation
jade-neoforge = "5427817" # 1.21-15.0.4-neoforge
jade-fabric = "5427840" # 1.21-15.0.4-fabric
badpackets-forge = "forge-0.8.1"
badpackets-neoforge = "neo-0.8.1"
badpackets-fabric = "fabric-0.8.1"
curios = "9.5.1+1.21.1"
cobblemon-common = "Uz1QF4Md" # neoforge-1.7.1+1.21.1
cobblemon-neoforge = "Uz1QF4Md" # neoforge-1.7.1+1.21.1
cobblemon-fabric = "s64m1opn" # fabric-1.7.1+1.21.1

[libraries]
minecraft-forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
minecraft-neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }
minecraft-fabric = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
forgeconfigapiport-common = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi", version.ref = "forgeconfigapiport" }
forgeconfigapiport-fabric = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-fabric", version.ref = "forgeconfigapiport" }
forgeconfigapiport-forge = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-forge", version.ref = "forgeconfigapiport" }
wthit-common = { module = "mcp.mobius.waila:wthit", version.ref = "wthit-common" }
wthit-forge = { module = "mcp.mobius.waila:wthit", version.ref = "wthit-forge" }
wthit-neoforge = { module = "mcp.mobius.waila:wthit", version.ref = "wthit-neoforge" }
wthit-fabric = { module = "mcp.mobius.waila:wthit", version.ref = "wthit-fabric" }
jade-common = { module = "curse.maven:jade-324717", version.ref = "jade-common" }
jade-forge = { module = "curse.maven:jade-324717", version.ref = "jade-forge" }
jade-neoforge = { module = "curse.maven:jade-324717", version.ref = "jade-neoforge" }
jade-fabric = { module = "curse.maven:jade-324717", version.ref = "jade-fabric" }
badpackets-forge = { module = "lol.bai:badpackets", version.ref = "badpackets-forge" }
badpackets-neoforge = { module = "lol.bai:badpackets", version.ref = "badpackets-neoforge" }
badpackets-fabric = { module = "lol.bai:badpackets", version.ref = "badpackets-fabric" }
curios-neoforge = { module = "top.theillusivec4.curios:curios-neoforge", version.ref = "curios" }
cobblemon-common = { module = "maven.modrinth:cobblemon", version.ref = "cobblemon-common" }
cobblemon-neoforge = { module = "maven.modrinth:cobblemon", version.ref = "cobblemon-neoforge" }
cobblemon-fabric = { module = "maven.modrinth:cobblemon", version.ref = "cobblemon-fabric" }

[plugins]
modpublishplugin = { id = "me.modmuss50.mod-publish-plugin", version = "0.6.3" }
vanillagradle = { id = "org.spongepowered.gradle.vanilla", version = "0.2.1-SNAPSHOT" }
forgegradle = { id = "net.minecraftforge.gradle", version = "[6.0.16,6.2)" }
fabricloom = { id = "fabric-loom", version = "1.7-SNAPSHOT" }
moddevgradle = { id = "net.neoforged.moddev", version = "2.0.5-beta" }
mixingradle = { id = "org.spongepowered.mixin", version = "0.7.+" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.1.7" }
