modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mixins]]
config = "shouldersurfing.common.mixins.json"

[[mixins]]
config = "shouldersurfing.common.compat.mixins.json"

[[mixins]]
config = "shouldersurfing.neoforge.mixins.json"

[[mixins]]
config = "shouldersurfing.neoforge.compat.mixins.json"

[[mods]]
modId = "${modId}"
version = "${minecraftVersion}-${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
credits = "${modContributors}"
description = "${modDescription}"
logoFile = "logo.png"
displayURL = "${modUrl}"
displayTest = "NONE"

[[dependencies.${modId}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "neoforge"
type = "required"
versionRange = "[21.11.0-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "betterthirdperson"
type = "incompatible"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "camerautils"
type = "incompatible"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "nimble"
type = "incompatible"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "valkyrienskies"
type = "incompatible"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "customcameraview"
type = "incompatible"
side = "CLIENT"
