modLoader = "javafml"
loaderVersion = "[4,)"
displayURL = "${modUrl}"
logoFile = "logo.png"
authors = "${modAuthor}"
license = "MIT"

[[mixins]]
config = "shouldersurfing.common.mixins.json"

[[mixins]]
config = "shouldersurfing.common.compat.mixins.json"

[[mixins]]
config = "shouldersurfing.compat.oculus.mixins.json"

[[mods]]
modId = "${modId}"
displayName = "${modName}"
version = "${minecraftVersion}-${modVersion}"
description = "${modDescription}"
displayTest = "NONE"

[[dependencies.${modId}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "forgeconfigapiport"
type = "required"
versionRange = "[21.0.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "betterthirdperson"
type = "incompatible"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "camerautils"
type = "incompatible"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "nimble"
type = "incompatible"
side = "CLIENT"

[[dependencies.${modId}]]
modId = "valkyrienskies"
type = "incompatible"
side = "CLIENT"