name: Publish to Platform

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
        description: "Java version to use for publishing"
      platform:
        required: true
        type: string
        description: "Platform to publish to (curseforge, modrinth)"
      publish-task:
        required: true
        type: string
        description: "Gradle task to run for publishing"
      artifact-name:
        required: false
        type: string
        default: "mod-jars"
        description: "Name of the artifact to download"
      extra-params:
        required: false
        type: string
        default: ""
        description: "Extra parameters for the Gradle task"
    secrets:
      CURSE_API_KEY:
        required: true
        description: "API token for CURSE FORGE"
      MODRINTH_API_KEY:
        required: true
        description: "API token for MODRINTH"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: gradle

      - name: Gradle Cache
        id: gradle-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/notifications
            ~/.gradle/wrapper
            **/.gradle
            **/build/downloadMCMeta
            **/build/moddev
            **/build/tmp
            **/loom-cache
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('gradle/libs.versions.toml', '**/accesstransformer.cfg', '**/*.accesswidener') }}

      - name: Publish to ${{ inputs.platform }}
        env:
          CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
        run: |
          ./gradlew --build-cache ${{ inputs.publish-task }} \
            ${{ inputs.extra-params }}
